### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by ghost** [icyphox/vite#3]
I see that Markdown is supported:

https://github.com/icyphox/vite#specifying-per-page-templates

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by icyphox** [comment]
Nope, and it likely won't be. Since I built vite for me and I don't use reST,
I don't really want to add support
for it. However, you are welcome to shoot
a PR. :)


--
Anirudh Oppiliappan
https://icyphox.sh


11-Jan-2020 2:31:09 am Steven Penny <notifications@github.com>:
